fix: 18 decimals, add .await, update UncheckedExtrinsic
r0gue-io/evm-parachain pull request #6
Opened 2024-05-09 05:13 UTC by peterwht

2024-05-10 13:29 UTC, AlexD10S approved these changes

2024-05-10 13:30 UTC, AlexD10S commented
Amazing!

2024-05-11 07:22 UTC, AlexD10S approved these changes
Tested after the rebase and works!

Only doubt is about the renaming of `parachain-template-runtime`to  `frontier-parachain-runtime` in the code.
I changed to `parachain-template-runtime` to keep consistency with the node binary name. The binary name has to be `parachain-template-node`, so when we generate the Zombienet config file with `pop-cli`, it works.

Just my opinion, if you keep it here, then we can merge: https://github.com/r0gue-io/evm-parachain/pull/4. Otherwise we can close that PR

2024-05-11 09:02 UTC, Daanvdplas commented on runtime/src/lib.rs
> +/// Given the 500ms Weight, from which 75% only are used for transactions,
This is incorrect, this is 2 seconds

2024-05-11 09:04 UTC, Daanvdplas approved these changes
Didn't deploy a smart contract on it but Alex and Peter have done successfully

2024-05-11 10:37 UTC, AlexD10S commented
> I don't understand though why we change the names to frontier, and in #4 we change it back.

It closed the other PR to avoid more confusion. It made sense when it was opened but not after the merge or your PR where naming was changed already: https://github.com/r0gue-io/evm-parachain/pull/11/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R32.

The binary name has to be called `parachain-template-node`, so when we generate the Zombienet config file with pop-cli, it works without changing anything.

For consistency I would prefer to keep `parachain-template-runtime` too instead of `frontier-parachain-runtime`

2024-05-11 14:33 UTC, Daanvdplas requested changes
Change `frontier-parachain` to `parachain-template` naming

2024-05-12 11:00 UTC, AlexD10S approved these changes

2024-05-12 16:23 UTC, Daanvdplas approved these changes
LGTM!

2024-05-13 06:50 UTC, merged